### ISSUE TITLE
Build error with giro class

### ISSUE THREAD

**Issue by petterreinholdtsen** [asgeirn/brev-cls#7]
I'm trying to use the giro class, but building (also with the example giro.tex) like this:

```
! Undefined control sequence.
<argument> \textocrb 
                     {\fromaccount }
l.28 \end{giro}
               
?
```

Any idea what is going wrong here?

**Comment by asgeirn** [comment]
Probably related to the OCR-B font it wants to use on the giro strip (the one with kid, amount and account number).  This control sequence used to activate that font.
I'll research where this font has moved.

**Comment by asgeirn** [comment]
@petterreinholdtsen could you test with the latest commit, whether this works?

**Comment by petterreinholdtsen** [comment]
[Asgeir Storesund Nilsen]
> @petterreinholdtsen could you test with the latest commit, whether
> this works?

Still failing.  I get this when I run pdflatex giro.tex:

This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./giro.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-01-09> xparse <2020-03-03> (./giro.cls
Document Class: giro 2022/05/09 v1.7 Klasse for utfylling av giro
(/usr/share/texlive/texmf-dist/tex/latex/base/letter.cls
Document Class: letter 2020/03/11 v1.3b Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def))
(/usr/share/texlive/texmf-dist/tex/generic/babel-norsk/norsk.ldf))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/latin1.def))
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file giro.aux.

Underfull \hbox (badness 10000) in paragraph at lines 13--13


Underfull \hbox (badness 10000) in paragraph at lines 13--13


Overfull \hbox (5.20201pt too wide) in paragraph at lines 18--28
[][]

Underfull \hbox (badness 10000) in paragraph at lines 18--28

(/usr/share/texlive/texmf-dist/tex/latex/ocr-latex/ot1ocrb.fd)
kpathsea: Running mktextfm ocrb10
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input ocrb10
This is METAFONT, Version 2.7182818 (TeX Live 2020/Debian) (preloaded base=mf)


kpathsea: Running mktexmf ocrb10
! I can't find file `ocrb10'.
<*> ...ljfour; mag:=1; ; nonstopmode; input ocrb10
                                                  
Please type another input file name
! Emergency stop.
<*> ...ljfour; mag:=1; ; nonstopmode; input ocrb10
                                                  
Transcript written on mfput.log.
grep: ocrb10.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input ocrb10' failed to make ocrb10.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font OT1/ocrb/m/n/10=ocrb10 at 10.0pt not loadable: Metric (TFM) file not fou
nd.
<to be read again> 
                   relax 
l.28 \end{giro}
               
? 

--
Happy hacking
Petter Reinholdtsen

**Comment by asgeirn** [comment]
Did you install the `texlive-fonts-extra` package?  Is this available in Debian?

I just confirmed `pdflatex giro` produced a PDF using /usr/share/texlive/texmf-dist/fonts/type1/public/ocr-b-outline/ocrb10.pfb on Ubuntu 20.04.

**Comment by petterreinholdtsen** [comment]
[Asgeir Storesund Nilsen]
> Did you install the `texlive-fonts-extra` package?  Is this available
> in Debian?

I do not have it installed.  Notice installing it will use 1.5 GiB of
disk space, which might be the reason I do not have it installed.  It is
available on Debian.


> I just confirmed `pdflatex giro` produced a PDF using
> /usr/share/texlive/texmf-dist/fonts/type1/public/ocr-b-outline/ocrb10.pfb
> on Ubuntu 20.04.

Right, thanks.  I think I will add it as suggest to the Debian package.

-- 
Happy hacking
Petter Reinholdtsen
